INSERT INTO BUG (ID_BUG,AVANCEMENT,DATE_CREATION,DESCRIPTION,PRIORITE,TITRE) VALUES
  (1,'TODO',TO_DATE('01-01-2020', 'dd-MM-yyyy'),'bdfhsfish','HAUTE','bug1');
  
INSERT INTO BUG (ID_BUG,AVANCEMENT,DATE_CREATION,DESCRIPTION,PRIORITE,TITRE) VALUES
  (2,'TODO',TO_DATE('01-01-2020', 'dd-MM-yyyy'),'bdfhsfish','BASSE','bug2');
  
INSERT INTO BUG (ID_BUG,AVANCEMENT,DATE_CREATION,DESCRIPTION,PRIORITE,TITRE) VALUES
  (3,'EN COURS',TO_DATE('01-01-2020', 'dd-MM-yyyy'),'bdfhsfish','BASSE','bug3');
  
INSERT INTO BUG (ID_BUG,AVANCEMENT,DATE_CREATION,DESCRIPTION,PRIORITE,TITRE) VALUES
  (4,'EN COURS',TO_DATE('01-01-2020', 'dd-MM-yyyy'),'bdfhsfish','BASSE','bug4');
  
INSERT INTO BUG (ID_BUG,AVANCEMENT,DATE_CREATION,DESCRIPTION,PRIORITE,TITRE) VALUES
  (5,'EN COURS',TO_DATE('01-01-2020', 'dd-MM-yyyy'),'bdfhsfish','BASSE','bug5');
  
INSERT INTO BUG (ID_BUG,AVANCEMENT,DATE_CREATION,DESCRIPTION,PRIORITE,TITRE) VALUES
  (6,'TERMINE',TO_DATE('01-01-2020', 'dd-MM-yyyy'),'bdfhsfish','BASSE','bug6');
  
  

  INSERT INTO DEVELOPPEUR (ID_DEV,AVATAR,NOM) VALUES
  (1,'https://lesexpertsdurecouvrement.com/wp-content/uploads/2015/11/default-avatar-596x596.jpg','Test prenom');